# Generated by Django 4.2.7 on 2023-11-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_in_post_content',
            field=models.BooleanField(default=True, help_text='Exiba a imagem de capa também dentro do conteúdo do post,         se marcado.'),
        ),
    ]
